Repository profluiscaparroz/analise-de-dados, pull requests merged in 2025-02, with the labels that each got.

#2 Adiciona introdução para a disciplina de análise de dados
  README.md
  README.pdf
  topicos/01-introducao/README.md
  topicos/01-introducao/README.pdf
  topicos/02-estatistica/README.md
  topicos/02-estatistica/README.pdf
Labels: new class

#5 Adicione dataset e aula sobre distribuição de frequencia
  README.pdf
  topicos/02-estatistica/01-distribuicao-frequencia/README.md
  topicos/02-estatistica/01-distribuicao-frequencia/README.pdf
  topicos/02-estatistica/01-distribuicao-frequencia/arquivos/python/exemplo_distribuicao_frequencia.ipynb
  topicos/02-estatistica/01-distribuicao-frequencia/arquivos/python/exemplo_gerar_dataset.ipynb
  topicos/dataset/csv/alunosNotas.csv
  topicos/dataset/csv/amostraPopulacao.csv
  topicos/dataset/csv/dadosAlunos.csv
  topicos/dataset/csv/dsfaltas/faltasAlunos1.csv
  topicos/dataset/csv/dsfaltas/faltasAlunos2.CSV
  topicos/dataset/csv/dsfaltas/faltasAlunos3.csv
  topicos/dataset/csv/dsfaltas/faltasAlunos4.csv
  topicos/dataset/csv/dsfaltas/faltasAlunos5.csv
  topicos/dataset/csv/dsfaltas/faltasAlunos6.csv
  topicos/dataset/csv/faltasAlunos.csv
  topicos/dataset/csv/questionario.csv
  topicos/dataset/csv/resumoAlunos.csv
  topicos/dataset/excel/alunosNotas.xlsx
  topicos/dataset/excel/amostraPopulacao.xlsx
  topicos/dataset/excel/dadosAlunos.xlsx
  topicos/dataset/excel/faltasAlunos.xlsx
  topicos/dataset/excel/resumoAlunos.xlsx
  topicos/dataset/movie lens/links.csv
  topicos/dataset/movie lens/movies.csv
  topicos/dataset/movie lens/ratings.csv
  topicos/dataset/movie lens/tags.csv
Labels: enhancement, new class

#6 Ajuste fórmulas no arquivo
  topicos/02-estatistica/01-distribuicao-frequencia/README.md
  topicos/02-estatistica/01-distribuicao-frequencia/README.pdf
  topicos/02-estatistica/README.md
  topicos/02-estatistica/README.pdf
Labels: bug

#7 Adicione o arquivo para explicar tendencia centrais
  topicos/02-estatistica/02-tendencias-centrais/README.md
  topicos/02-estatistica/02-tendencias-centrais/README.pdf
Labels: new class

#9 Adicione explicação médias
  topicos/02-estatistica/02-tendencias-centrais/README.md
  topicos/02-estatistica/02-tendencias-centrais/README.pdf
Labels: new class
