Repository profluiscaparroz/analise-de-dados, pull requests merged in 2025-04, with the labels that each got.

#17 Aula/tipos graficos
  topicos/02-estatistica/04-medidas-separatrizes-dispersao/README.md
  topicos/02-estatistica/04-medidas-separatrizes-dispersao/README.pdf
Labels: bug, documentation, duplicate

#19 Aula/tipos graficos
  topicos/0-lista-simbolos/README.md
  topicos/0-lista-simbolos/README.pdf
  topicos/02-estatistica/04-medidas-separatrizes-dispersao/04_notas_aula_medidas_separatrizes.ipynb
  topicos/02-estatistica/04-medidas-separatrizes-dispersao/04_notas_aula_medidas_separatrizes_e_dispersao.ipynb
  topicos/02-estatistica/05-tipo-amostragem/README.md
  topicos/02-estatistica/05-tipo-amostragem/README.pdf
  topicos/02-estatistica/README.md
  topicos/02-estatistica/README.pdf
  topicos/distribuicao/README.md
  topicos/distribuicao/README.pdf
Labels: documentation, enhancement

#20 Atualiza o README.md com novas seções sobre cálculo de tamanho de amostra
  topicos/distribuicao/README.md
  topicos/distribuicao/README.pdf
Labels: documentation

#22 Aula/tipos graficos
  topicos/03-probabilidade/01-tipo-amostragem/README.md
  topicos/03-probabilidade/01-tipo-amostragem/README.pdf
  topicos/03-probabilidade/02-combinatoria-permuta/README.md
  topicos/03-probabilidade/02-combinatoria-permuta/README.pdf
  topicos/distribuicao-weibull/docs/README.md
  topicos/distribuicao-weibull/docs/README.pdf
  topicos/distribuicao-weibull/src/explicacao-weibull.ipynb
Labels: new class

#23 Adiciona explicação sobre fatorial, permutacao, arranjo e combinação
  topicos/03-probabilidade/02-combinatoria-permuta/README.md
  topicos/03-probabilidade/02-combinatoria-permuta/README.pdf
  topicos/distribuicao-weibull/docs/README.md
  topicos/distribuicao-weibull/docs/README.pdf
  topicos/distribuicao-weibull/src/explicacao_weibull.ipynb
  topicos/distribuicao/README.md
  topicos/distribuicao/README.pdf
Labels: new class

#24 Aula/probabilidade evento
  topicos/03-probabilidade/02-combinatoria-permuta/README.md
  topicos/03-probabilidade/02-combinatoria-permuta/README.pdf
  topicos/03-probabilidade/03-probabilidade/README.md
  topicos/03-probabilidade/03-probabilidade/README.pdf
Labels: duplicate

#25 Aula/probabilidade evento
  topicos/03-probabilidade/01-tipo-amostragem/README.md
  topicos/03-probabilidade/01-tipo-amostragem/README.pdf
  topicos/03-probabilidade/03-probabilidade/README.md
  topicos/03-probabilidade/03-probabilidade/README.pdf
  topicos/03-probabilidade/03-probabilidade/img/lei_dos_grandes_numeros.png
  topicos/03-probabilidade/03-probabilidade/img/ponto_amostral.png
Labels: new class
